### ISSUE TITLE
5.x subpackage not uploaded on anaconda.org

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/clangdev-feedstock#41]
For the `clang_variant` subpackage in the 5.x branch, the anaconda upload command does not succeed because of a wrong filename.

```
[ERROR] File "/home/conda/feedstock_root/build_artifacts/linux-64/clang_variant-1.0-defaulthe4b91f6.tar.bz2" does not exist
Traceback (most recent call last):
  File "/opt/conda/bin/upload_package", line 11, in <module>
    sys.exit(upload_package())
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda_forge_ci_setup/build_utils.py", line 82, in upload_package
    upload_or_check(recipe_root, owner, channel, [config_file])
  File "/opt/conda/lib/python3.6/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 135, in upload_or_check
    upload(token_fn, path, owner, channel)
  File "/opt/conda/lib/python3.6/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 65, in upload
    env=os.environ)
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', '/tmp/tmpxrmxnnr4/binstar.token', 'upload', '/home/conda/feedstock_root/build_artifacts/linux-64/clang_variant-1.0-defaulthe4b91f6.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1.
Exited with code 1
```

The issue appears to be that it tries uploading `clang_variant-1.0-defaulthe4b91f6.tar.bz2` while it should be `clang_variant-1.0-default.tar.bz2`.

**Comment by SylvainCorlay** [comment]
The anaconda upload command suggested by conda-build appears to be ok, so it is probably a bug in conda-smithy.

```
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:

anaconda upload /home/conda/feedstock_root/build_artifacts/linux-64/clang_variant-1.0-default.tar.bz2
anaconda upload /home/conda/feedstock_root/build_artifacts/linux-64/clangdev-5.0.0-h4e674e7_0.tar.bz2
```

**Comment by SylvainCorlay** [comment]
cc @mingwandroid this appears to be a conda-build bug.

In https://github.com/conda/conda-build/blob/a6e3a33c6588f89db4d81ec25cb637fcf54d1f78/conda_build/metadata.py#L1260, the `build_id` appears to not take into account the specified build string.

**Comment by SylvainCorlay** [comment]
I don't see another solution than to drop subpackages which appear to expose some bugs in conda-build.

**Comment by hmaarrfk** [comment]
Not sure if it is related, but a while back I needed to issue this PR:
https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/28

**Comment by SylvainCorlay** [comment]
I think that we can close this one.
